---
README: |
    Config for word-array games such as Scrabble and Words With Friends
introduction: |
    Welcome to WordSquareGame!
board_layout: layout_scrabble
dictionary_file: /usr/share/dict/words
logfile_basename: smaven
counts2chars: count2chars_scrabble_en
points2chars: points2chars_scrabble_en
player_colors:
    - 1: "aqua"
    - 2: "tangerine"
player_count: 2
rack_size: 7
bingo_points: 50
config_hrule1: ########## ########## ########## ########## ########## ##########
layout_scrabble: |
    #..2...#...2..#
    .@...3...3...@.
    ..@...2.2...@..
    2..@...2...@..2
    ....@.....@....
    .3...3...3...3.
    ..2...2.2...2..
    #..2...*...2..#
    ..2...2.2...2..
    .3...3...3...3.
    ....@.....@....
    2..@...2...@..2
    ..@...2.2...@..
    .@...3...3...@.
    #..2...#...2..#
layout_wwf: |
    ...#..3.3..#...
    ..2..@...@..2..
    .2..2.....2..2.
    #..3...@...3..#
    ..2...2.2...2..
    .@...3...3...@.
    3...2.....2...3
    ...@...*...@...
    3...2.....2...3
    .@...3...3...@.
    ..2...2.2...2..
    #..3...@...3..#
    .2..2.....2..2.
    ..2..@...@..2..
    ...#..3.3..#...
layout_wwf_challenge: |
    3.#.....#.3
    .@...@...@.
    #.2.2.2.2.#
    ...3...3...
    ..2.....2..
    .@...*...@.
    ..2.....2..
    ...3...3...
    #.2.2.2.2.#
    .@...@...@.
    3.#.....#.3
config_hrule2: ########## ########## ########## ########## ########## ##########
count2chars_scrabble_en:
    1: "kjqxz"
    2: "_bcfhmpvwy"
    3: "g"
    4: "dlsu"
    6: "nrt"
    8: "o"
    9: "ai"
    12: "e"
count2chars_wwf_en:
    1: "jkqxz"
    2: "_bcfmpvwy"
    3: "g"
    4: "hlu"
    5: "s"
    6: "r"
    7: "t"
    8: "io"
    9: "a"
    13: "e"
points2chars_scrabble_en:
    0: "_"
    1: "aeilnorstu"
    2: "dg"
    3: "bcmp"
    4: "fhvwy"
    5: "k"
    8: "jx"
    10: "qz"
points2chars_wwf_en:
    0: "_"
    1: "aeiorst"
    2: "dlnu"
    3: "ghy"
    4: "bcfmpw"
    5: "kv"
    8: "x"
    10: "jqz"
config_hrule3: ########## ########## ########## ########## ########## ##########
help_command_syntax: |
    Command syntax:
        help                  - Show this help message
        show                  - Show the game state again
        across <word> <x> <y> - Place a word on the board, starting at <x>, <y>
        down   <word> <x> <y> - Form one or more words on the board
            Note: (0, 0) represents the upper-left corner
            Note: Enter blanks as upper-case, and others as lower-case
        swap <letters>        - Swap letters from your rack with ones in the bag
        pass                  - Pass on this round
        resign                - Accept defeat; give your opponent the win
config_hrule4: ########## ########## ########## ########## ########## ##########
test_board_scrabble: |
    ...............
    ...............
    ...............
    ...............
    ........a......
    ......a.p......
    ......p.p......
    .....apple.....
    ......l.e......
    ......e........
    ...............
    ...............
    ...............
    ...............
    ...............
test_name1: Amy
test_name2: Bob
test_rack1: caiolmss
test_rack2: axquick

