---
README: |
    Config for word-array games such as Scrabble and Words With Friends
introduction: |
    Welcome to WordSquareGame!
board_layout: board_layout_scrabble
letter_counts: letter_counts_scrabble_en
letter_points: letter_points_scrabble_en
player_colors:
    - 1: "aqua"
    - 2: "tangerine"
player_count: 2
board_layout_scrabble: |
    T..d...T...d..T
    .D...t...t...D.
    ..D...d.d...D..
    d..D...d...D..d
    ....D.....D....
    .t...t...t...t.
    ..d...d.d...d..
    T..d...*...d..T
    ..d...d.d...d..
    .t...t...t...t.
    ....D.....D....
    d..D...d...D..d
    ..D...d.d...D..
    .D...t...t...D.
    T..d...T...d..T
board_layout_scrabble: |
    ...T..t.t..T...
    ..d..D...D..d..
    .d..d.....d..d.
    T..t...D...t..T
    ..d...d.d...d..
    .D...t...t...D.
    t...d.....d...t
    ...D...*...D...
    t...d.....d...t
    .D...t...t...D.
    ..d...d.d...d..
    T..t...D...t..T
    .d..d.....d..d.
    ..d..D...D..d..
    ...T..t.t..T...
letter_counts_scrabble_en:
    - 1: "kjqxz"
    - 2: " bcfhmpvwy"
    - 3: "g"
    - 4: "dlsu"
    - 6: "nrt"
    - 8: "o"
    - 9: "ai"
    - 12: "e"
letter_counts_wwf_en:
    - 1: "jkqxz"
    - 2: " bcfmpvwy"
    - 3: "g"
    - 4: "hlu"
    - 5: "s"
    - 6: "r"
    - 7: "t"
    - 8: "io"
    - 9: "a"
    - 13: "e"
letter_points_scrabble_en:
    - 0: " "
    - 1: "aeilnorstu"
    - 2: "dg"
    - 3: "bcmp"
    - 4: "fhvwy"
    - 5: "k"
    - 8: "jx"
    - 10: "qz"
letter_points_wwf_en:
    - 0: " "
    - 1: "aeiorst"
    - 2: "dlnu"
    - 3: "ghy"
    - 4: "bcfmpw"
    - 5: "kv"
    - 8: "x"
    - 10: "jqz"
